src/reqs.c
src/reverse-proxy.c

Hi,
As indicated by Michael Adam, a new pull request with rewritten code.
Kind regards,
Stephan

Continue with forward proxy if ReverseOnly is not true and no mapping available

---

configure.ac

build: remove foreign from AM_INIT_AUTOMAKE - generate INSTALL again

---

Makefile.am

build: add README.md to the bundled files

---

.travis.yml

Enable travis-ci: add .travis.yml

---

README.md

README: mention --enable-reverse configure option

---

.gitignore

add 'compile' to gitignore

---

src/hashmap.c
src/hashmap.h
src/html-error.c

Split changes from [PR#59](https://github.com/tinyproxy/tinyproxy/pull/59).

Move lookup_variable from html-error.c to hashmap.c

---

README.md

tinyproxy configure does not actually support enable-static

---

src/conf.c

PR requested in https://github.com/tinyproxy/tinyproxy/issues/15

Issue 15 fix. PR

---

configure.ac

activate reverse proxy support by default

---

src/main.c

Fix CVE-2017-11747: Create PID file before dropping privileges.

---

src/transparent-proxy.c

Fixed 1 possible memory leak in build_url #141

fix possible memory leak

---

src/reqs.c

just like the rest of the socks code, this was stolen from
proxychains-ng, of which i'm happen to be the maintainer of,
so it's not an issue (the licenses are identical, too).

implement user/password auth for socks5 upstream proxy

---

src/basicauth.c

fix basicauth string comparison

---

src/sock.c

Use gai_strerror() or strerror() depending on the return value of getaddrinfo() and getnameinfo() for a proper failure report.
See https://man.openbsd.org/gai_strerror.3

Use gai_strerror() to report errors of getaddrinfo() and getnameinfo()

---

.github/workflows/main.yml

Add github actions workflow for new CI

---

.github/workflows/main.yml

github actions: add macos tests

---

.github/workflows/main.yml

github actions: don't run "make test" on macos it currenctly fails

---

.github/ISSUE_TEMPLATE/new-issue--bug-report--question.md

i'm tired of getting the same bug report for old tinyproxy versions over and over, and people not even stating which version they're using.

Add an issue template

---

src/reqs.c

while at it, the function doing it was renamed from the misleading
ssl name to what it actually does.
also inlined the strings that were previously defined as macros.
addressing #152

echo http protocol version on CONNECT request response

---

src/reqs.c

if tinyproxy serves as a HTTP server (i.e. when serving stats), use error code 401, else error code 407.
fixes #532

basic auth: fix error status 401 vs 407
