configure.ac, docs/man5/Makefile.am, docs/man8/Makefile.am
`make dist` now creates the manpages and puts them into the tarball, so
the user does not need to have `a2x` installed to build them.
closes #2
=> ship manpages as part of the dist tarball

configure.ac, docs/man5/Makefile.am, docs/man8/Makefile.am
Copied some build fixes from Homebrew and moved lookup_variable from html-error.c to hashmap.c so it can be used elsewhere.
=> Fix OS X build

src/child.c
A proposed fix for the logrotate SIGHUP issue.
=> Prevent child from calling exit() on interrupt

etc/tinyproxy.conf.in
tinyproxy conservatively defaulted to allow CONNECT method only
on two ports used by SSL in the ancient past, but since HTTPS usage
got much more widespread (actually, it's now the default for the
majority of websites), it makes sense now to allow it without
restriction by default to accomodate for the new situation.
=> tinyproxy.conf.in: default to allow CONNECT method more broadly

configure.ac
i am sorry, but this one has to go, it causes too much frustration.
i can live with having myself restricted to use only the C89 dialect (even though it doesn't make much sense to me either), and using all sorts of pedantic warnings, but C++ compat goes too far.
=> configure.ac: remove -Wc++-compat

src/network.c, src/network.h
if using one of unsigned or signed char for the function prototype, one
gets nasty warnings when using it with the other type. the only proper
solution is to put void* into the prototype, and then specialize the pointer
inside the function using an automatic variable.
for exactly this reason, libc functions like read(), write(), etc use void*
too.
this is a prerequisite for getting the socks proxy support, the upstream auth, and the basic auth patches merged (to build them without warnings).
=> safe_write/read: take void* buffer for generic use

etc/tinyproxy.conf.in, src/conf.c, src/reqs.c, src/upstream.c, src/upstream.h
original patch submitted in 2006 to debian mailing list:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=392848%29#12
this version was rebased to git and updated by Russ Dill <russ.dill@gmail.com>
in 2015 (the original patch used a different config file format).
as discussed in #40.
commit message by @rofl0r.
=> add SOCKS upstream proxy support (socks4/socks5)

etc/tinyproxy.conf.in, src/Makefile.am, src/base64.c, src/base64.h, src/basicauth.c, src/basicauth.h, src/conf.c, src/conf.h, src/html-error.c, src/reqs.c
using the "BasicAuth" keyword in tinyproxy.conf.
base64 code was written by myself and taken from my own library "libulz".
for this purpose it is relicensed under the usual terms of the tinyproxy
license.
=> add support for basic HTTP authentication

src/conf.c
The configure.ac file was missing a check for syslog.h, preventing the syslog feature from being enabled.
=> Remove #ifdef for syslog.h

etc/tinyproxy.conf.in, src/basicauth.c, src/basicauth.h, src/conf.c, src/reqs.c, src/upstream.c, src/upstream.h
superseding #38 and #96
after merge, i will refactor the upstream directive to look like
```
upstream http foo:bar@localhost:9999 "invalid.domain"
upstream socks5 freeproxy.com:1080
upstream socks4 localhost:9050
```
and add upstream authentication for socks too.
right now, the upstream4 and upstream5 directives look quite ugly, imo.
@gbasto and @valenbg1 : please test
=> add support for upstream with basic http auth

configure.ac, docs/man5/tinyproxy.conf.txt.in, etc/tinyproxy.conf.in, src/conf.c, src/reqs.c, src/upstream.c, src/upstream.h
merges upstream syntax together:
before:
```
upstream httpproxy:8080 "domain"
upstream otherproxy:8080
upstream user:pass@httpproxy:8080 "domain"
upstream4 socks4proxy:9050 "domain"
upstream5 socks5proxy:1080 "domain"
no upstream "otherdomain"
```
after:
```
upstream http httpproxy:8080 "domain"
upstream http otherproxy:8080
upstream http user:pass@httpproxy:8080 "domain"
upstream socks4 socks4proxy:9050 "domain"
upstream socks5 socks5proxy:1080 "domain"
upstream none "otherdomain"
```
=> Unified upstream

configure.ac
by having all features turned on by default, the binary is only
slightly bigger, but users of binary distros get the whole package
and don't need to compile tinyproxy by hand if they need a feature
that wasn't compiled in.
it also prevents the confusion from getting syntax errors when a
config file using those features is parsed.
another advantage is that by enabling them these features may
actually get some more testing.
=> enable transparent proxy by default

src/conf.c
closes #15 for real.
the previous patch that was merged[0] was halfbaked and only removed
the warning part of the original patch from openwrt[1], but didn't
actually activate bind support. further it invoked UB by removing
the return value from the function, if transparent proxy support was
compiled in.
[0]: d97d486d53ce214ae952378308292f333b8c7a36
[1]: https://gitlab.labs.nic.cz/turris/openwrt-packages/commit/7c01da4a72e6f0b7613a86529547659ea4007eba
=> make bind option usable with transparent proxy too

src/Makefile.am
sbin/ is meant for programs only usable by root, but in tinyproxy's
case, regular users can and *should* use tinyproxy; meaning it is
preferable from a security PoV to use tinyproxy as regular user.
=> install tinyproxy to bin/, not /sbin

src/upstream.c
=> upstream: Fix case of empty string domain.

src/html-error.c
This silences a gcc v7 compile warning.
=> html-error: Make a switch fallthrough explicit

src/reqs.c
RFC 1929 specifies that the user/pass auth subnegotation repurposes the version
field for the version of that specification, which is 1, not 5.
however there's quite a good deal of software out there which got it wrong and
replies with version 5 to a successful authentication, so let's just accept both
forms - other socks5 client programs like curl do the same.
closes #172
this seems to be a common issue... i fixed the same bug today in proxychains-ng and microsocks.
https://github.com/rofl0r/proxychains-ng/commit/49d8ac933894a3eddaea387cfc62d70661fb7cf4
https://github.com/rofl0r/microsocks/commit/1998a16a23a6a15fff7de91220b698efb9040ee8
=> fix socks5 upstream user/pass subnegotiation check

src/conf.c
Restricting password to be alphanumeric is strange at the very least... This change proposes to lift this limitation and only ban ":" and "@" (so we can distinguish username on the left and host on the right).
This works on my local machine just fine.
=> Added way more liberty on password value

src/child.c
it was reported that because the fdset was only initialized once,
tinyproxy would fail to properly listen on more than one interface.
closes #214
closes #127
=> child.c: properly initialize fdset for each select() call

src/filter.c
This patch is related to parsing the filter file.
The new code skips leading whitespaces before removing trailing
whitespaces and comments.
Without doing this, lines with leading whitespace are treated like empty
lines (i.e. they are ignored).
=> filter: Don't ignore lines with leading whitespace

etc/tinyproxy.conf.in
Add the ::1 as 'allowed' in addition to 127.0.0.1, to deal with hosts that use IPv6 by default for localhost (such as on macOS 10.14.x and some Linux distros).
=> Fixes #256 Provides ::1 as allowed

src/child.c
I was hit by this, and did not see anything in the log, connections was just hanging.
Think "warning" is a better log level
=> Change loglevel for "Maximum number of connections reached"

docs/man5/tinyproxy.conf.txt.in
Following feature added in 8db511b9bff5dfa61a9448659e28ce54d9aa8869 .
If this is good, I suppose the man text output can be synced across to the Github Pages project for website?
=> Added BasicAuth to tinyproxy.conf man page

tests/scripts/run_tests.sh
Howdy,
It seems tinyproxy failed to build on hurd-i386 and a patch was contributed to solve that issue, this is said patch.
=> Fix FTBFS on hurd-i386: run_tests.sh duplicates build path.

src/reqs.c, src/sock.c, src/sock.h
the fix in 0b9a74c29036f9215b2b97a301b7b25933054302 was incomplete, as it
applied the socket timeout only to the socket received from accept(), but
not to sockets created for outgoing connections.
=> fix timeout not being applied to outgoing connections

etc/tinyproxy.conf.in, src/reqs.c, tests/scripts/run_tests.sh
Currently a 404 is returned for a misconfigured or unavailable upstream server.  Since that's a server error it should be a 5xx instead; a 404 is confusing when used as a forward proxy and might even be harmful when used as a reverse proxy.
It is debatable if another 5xx code might be better; the misconfigured situation might better be a 500 whereas the connection issue could be a 503 instead (as used eg. in haproxy).
=> Return 5xx when upstream is unreachable

src/conf.c
tinyproxy quits when it encounters the `XTinyProxy No` config directive and doesn't have support for it, even though it should only be an error when `XTinyProxy Yes` is configured.
=> Allow "XTinyProxy No" with xtinyproxy disabled

docs/man5/tinyproxy.conf.txt.in, src/conf.c
String config values matched by the STR regex must be enclosed in double quotes
Edit descriptions for brevity
conf.c: move boolean arguments comment before BOOL group
addresses #491
=> tinyproxy.conf.5: document config strings that require double quotes

configure.ac, docs/man8/Makefile.am, docs/man8/tinyproxy.txt.in, etc/Makefile.am, etc/tinyproxy.conf.in
Avoid using hardcoded paths in the man page, and use `runstatedir` for the run directory. I use the same approach used for `tinyproxy.conf`.
=> Use appropriate installation path variables

.github/workflows/shellcheck.yaml, Makefile.am, autogen.sh, tests/scripts/run_tests.sh, tests/scripts/run_tests_valgrind.sh
This adds shellcheck linting to the CI.
The purpose of this is to make sure the shell scripts in this repo don't have
syntactic or style issues known to shellcheck and to prevent future PRs from introducing regressions.
It additionally fixes issues in existing scripts while at it to prevent this from breaking the CI right away.
=> ci: add Shellcheck workflow
